fix failing test and try to publish test results in github action

diff --git a/.github/workflows/page.yml b/.github/workflows/page.yml
--- a/.github/workflows/page.yml
+++ b/.github/workflows/page.yml
@@ -33,6 +33,13 @@ jobs:
           distribution: 'temurin'
       - name: Tests
         run: ./gradlew allTests -x wasmJsBrowserTest
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test Results
+          path: build/test-results/**/*.xml
+          reporter: junit
       - name: Build and website
         run: ./gradlew wasmJsBrowserDistribution
       - name: Upload website artifact
